Traceback (most recent call last):
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
test <-  projectRaster(bioclim_hist_local, crs='EPSG:32718')
extent(test)
res(test)
------------------

Error in CRS(SRS_string = x): no arguments in initialization list
Traceback:

1. projectRaster(bioclim_hist_local, crs = "EPSG:32718")
2. .getCRS(crs)
3. CRS(SRS_string = x)
4. stop(res[[2]])
ERROR: Error in CRS(SRS_string = x): no arguments in initialization list


